/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg01.atividade.pratica;

/**
 *
 * @author Aluno
 */
public class CadastroPessoa extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPessoa
     */
    public CadastroPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCPF = new javax.swing.JLabel();
        edtCPF = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        cbbCargo = new javax.swing.JComboBox<>();
        cbbEstado = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        btImprimir = new javax.swing.JButton();
        pnlRodape = new javax.swing.JPanel();
        lblRodape = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulário Cadastro de Pessoa");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frmPessoa"); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 102, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Fomulário Cadastro de Pessoas");
        jLabel1.setName("lblTitulo"); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 102, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSeparator1.setName("lnSuperior"); // NOI18N

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(0, 0, 0));
        lblCPF.setText("Informe o CPF:");
        lblCPF.setName("lblCPF"); // NOI18N

        edtCPF.setBackground(new java.awt.Color(255, 255, 255));
        edtCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtCPF.setBorder(null);
        edtCPF.setName("edtCPF"); // NOI18N

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome:");
        lblNome.setName("lblNome"); // NOI18N

        edtEndereco.setBackground(new java.awt.Color(255, 255, 255));
        edtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtEndereco.setBorder(null);
        edtEndereco.setName("edtEndereco"); // NOI18N

        edtNome.setBackground(new java.awt.Color(255, 255, 255));
        edtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtNome.setBorder(null);
        edtNome.setName("edtNome"); // NOI18N

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(0, 0, 0));
        lblEndereco.setText("Endereço:");
        lblEndereco.setName("lblEndereco"); // NOI18N

        cbbCargo.setBackground(new java.awt.Color(255, 255, 255));
        cbbCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbCargo.setForeground(new java.awt.Color(255, 255, 255));
        cbbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDEFINIDO", "TI", "PROGRAMADOR", "MÉDICO", "PEDREIRO" }));
        cbbCargo.setBorder(null);
        cbbCargo.setName("cbbEstado"); // NOI18N

        cbbEstado.setBackground(new java.awt.Color(255, 255, 255));
        cbbEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbEstado.setForeground(new java.awt.Color(255, 255, 255));
        cbbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDEFINIDO", "MG", "SP", "MT", "RJ", "SC" }));
        cbbEstado.setBorder(null);
        cbbEstado.setName("cbbCargo"); // NOI18N

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(0, 0, 0));
        lblEstado.setText("Estado:");
        lblEstado.setName("lbEstado"); // NOI18N

        lblCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(0, 0, 0));
        lblCargo.setText("Cargo:");
        lblCargo.setName("lblCargo"); // NOI18N

        btImprimir.setBackground(new java.awt.Color(255, 102, 51));
        btImprimir.setForeground(new java.awt.Color(0, 0, 0));
        btImprimir.setText("Imprimir Pessoas");
        btImprimir.setName("btImprimir"); // NOI18N
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        pnlRodape.setBackground(new java.awt.Color(255, 102, 51));
        pnlRodape.setName("pnlRodape"); // NOI18N

        lblRodape.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRodape.setForeground(new java.awt.Color(0, 0, 0));
        lblRodape.setText("Desenvolvido por: Unifagoc @ Todos os direitos reservados 2026");
        lblRodape.setToolTipText("");
        lblRodape.setAlignmentX(0.5F);
        lblRodape.setName("lblCargo"); // NOI18N

        javax.swing.GroupLayout pnlRodapeLayout = new javax.swing.GroupLayout(pnlRodape);
        pnlRodape.setLayout(pnlRodapeLayout);
        pnlRodapeLayout.setHorizontalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRodapeLayout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(lblRodape)
                .addGap(255, 255, 255))
        );
        pnlRodapeLayout.setVerticalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRodape, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        lblRodape.getAccessibleContext().setAccessibleName("lblRodape");

        btCadastrar.setBackground(new java.awt.Color(255, 102, 51));
        btCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btCadastrar.setText("Cadastrar Pessoa");
        btCadastrar.setName("btCadastrar"); // NOI18N
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCPF)
                                    .addComponent(lblNome)
                                    .addComponent(lblEndereco)
                                    .addComponent(lblEstado)
                                    .addComponent(lblCargo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(edtCPF)
                                    .addComponent(edtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(cbbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 613, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(pnlRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCargo))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(pnlRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        
    }//GEN-LAST:event_btImprimirActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btImprimir;
    private javax.swing.JComboBox<String> cbbCargo;
    private javax.swing.JComboBox<String> cbbEstado;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRodape;
    private javax.swing.JPanel pnlRodape;
    // End of variables declaration//GEN-END:variables
}
