/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg01.atividade.pratica;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
  

    public class CadastroPessoa extends javax.swing.JFrame {

        /**
         * Creates new form CadastroPessoa
         */
        public CadastroPessoa() {
            initComponents();
            
        }

        gerirPessoas gp = new gerirPessoas();
        
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCPF = new javax.swing.JLabel();
        edtCPF = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        cbbCargo = new javax.swing.JComboBox<>();
        cbbEstado = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        btImprimir = new javax.swing.JButton();
        pnlRodape = new javax.swing.JPanel();
        lblRodape = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mmoDadosImpressao = new javax.swing.JTextArea();
        lblTituloImpressao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulário Cadastro de Pessoa");
        setBackground(new java.awt.Color(255, 153, 102));
        setName("frmPessoa"); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 102, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Fomulário Cadastro de Pessoas");
        jLabel1.setName("lblTitulo"); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 102, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSeparator1.setName("lnSuperior"); // NOI18N

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF.setText("Informe o CPF:");
        lblCPF.setName("lblCPF"); // NOI18N

        edtCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtCPF.setBorder(null);
        edtCPF.setName("edtCPF"); // NOI18N

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");
        lblNome.setName("lblNome"); // NOI18N

        edtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtEndereco.setBorder(null);
        edtEndereco.setName("edtEndereco"); // NOI18N

        edtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edtNome.setBorder(null);
        edtNome.setName("edtNome"); // NOI18N

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço:");
        lblEndereco.setName("lblEndereco"); // NOI18N

        cbbCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbCargo.setForeground(new java.awt.Color(255, 255, 255));
        cbbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDEFINIDO", "TI", "PROGRAMADOR", "MÉDICO", "PEDREIRO" }));
        cbbCargo.setBorder(null);
        cbbCargo.setName("cbbEstado"); // NOI18N

        cbbEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbEstado.setForeground(new java.awt.Color(255, 255, 255));
        cbbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDEFINIDO", "MG", "SP", "MT", "RJ", "SC" }));
        cbbEstado.setBorder(null);
        cbbEstado.setName("cbbCargo"); // NOI18N

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setText("Estado:");
        lblEstado.setName("lbEstado"); // NOI18N

        lblCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCargo.setText("Cargo:");
        lblCargo.setName("lblCargo"); // NOI18N

        btImprimir.setBackground(new java.awt.Color(255, 102, 51));
        btImprimir.setText("Imprimir Pessoas");
        btImprimir.setName("btImprimir"); // NOI18N
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        pnlRodape.setBackground(new java.awt.Color(255, 102, 51));
        pnlRodape.setName("pnlRodape"); // NOI18N

        lblRodape.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRodape.setText("Desenvolvido por: Unifagoc @ Todos os direitos reservados 2026");
        lblRodape.setToolTipText("");
        lblRodape.setAlignmentX(0.5F);
        lblRodape.setName("lblCargo"); // NOI18N

        javax.swing.GroupLayout pnlRodapeLayout = new javax.swing.GroupLayout(pnlRodape);
        pnlRodape.setLayout(pnlRodapeLayout);
        pnlRodapeLayout.setHorizontalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRodapeLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(lblRodape)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        pnlRodapeLayout.setVerticalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRodape, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblRodape.getAccessibleContext().setAccessibleName("lblRodape");

        btCadastrar.setBackground(new java.awt.Color(255, 102, 51));
        btCadastrar.setText("Cadastrar Pessoa");
        btCadastrar.setName("btCadastrar"); // NOI18N
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        mmoDadosImpressao.setColumns(20);
        mmoDadosImpressao.setRows(5);
        mmoDadosImpressao.setName("mmoDadosImpressao"); // NOI18N
        jScrollPane1.setViewportView(mmoDadosImpressao);

        lblTituloImpressao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloImpressao.setText("Dados de Cadastros");
        lblTituloImpressao.setName("lblTituloImpressao"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCPF)
                                            .addComponent(lblNome)
                                            .addComponent(lblEndereco)
                                            .addComponent(lblEstado)
                                            .addComponent(lblCargo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(edtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                            .addComponent(edtCPF)
                                            .addComponent(edtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                            .addComponent(cbbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(52, 52, 52)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloImpressao)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblTituloImpressao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEndereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCargo))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        
        String listaPessoa = "";
        
        listaPessoa = gp.listarPessoas();
        
        mmoDadosImpressao.setText(listaPessoa);        
        
    }//GEN-LAST:event_btImprimirActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed

    if (edtCPF.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo CPF é obrigatório!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        edtCPF.requestFocus();
        return;
    }

    if (edtNome.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo Nome é obrigatório!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        edtNome.requestFocus();
        return;
    }

    if (edtEndereco.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo Endereço é obrigatório!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        edtEndereco.requestFocus();
        return;
    }
    
    if (cbbEstado.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(this, "O campo Estado é obrigatório!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        cbbEstado.requestFocus();
        return;
    }
    
    if (cbbCargo.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(this, "O campo Cargo é obrigatório!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        cbbCargo.requestFocus();
        return;
    }

    JOptionPane.showMessageDialog(this, "Pessoa cadastrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);        

    String Nome = edtNome.getText();
    String CPF = edtCPF.getText();
    String Endereco = edtEndereco.getText();
    String Estado = cbbEstado.getItemAt(WIDTH);
    String Cargo = cbbCargo.getItemAt(WIDTH);

    dadosPessoa p = new dadosPessoa(Nome, CPF, Endereco, Estado, Cargo);

    gp.incluirPessoa(p);

    edtNome.setText("");
    edtCPF.setText("");
    edtEndereco.setText("");
    cbbCargo.setSelectedIndex(0);
    cbbEstado.setSelectedIndex(0);
    
    }//GEN-LAST:event_btCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btImprimir;
    private javax.swing.JComboBox<String> cbbCargo;
    private javax.swing.JComboBox<String> cbbEstado;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRodape;
    private javax.swing.JLabel lblTituloImpressao;
    private javax.swing.JTextArea mmoDadosImpressao;
    private javax.swing.JPanel pnlRodape;
    // End of variables declaration//GEN-END:variables
}
