/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg01.atividade.pratica;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
  

    public class CadastroPessoa extends javax.swing.JFrame {

        /**
         * Creates new form CadastroPessoa
         */
        public CadastroPessoa() {
            initComponents();
            setLocationRelativeTo(null);
        }

        gerirPessoas gp = new gerirPessoas();
        
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlImg = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        pgcOptions = new javax.swing.JMenuBar();
        pgArquivos = new javax.swing.JMenu();
        optNovo = new javax.swing.JMenuItem();
        optSair = new javax.swing.JMenuItem();
        pgRelatorio = new javax.swing.JMenu();
        pgInfo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulário Cadastro de Pessoa");
        setBackground(new java.awt.Color(255, 255, 102));
        setName("frmPessoa"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(400, 600));

        pnlFundo.setBackground(new java.awt.Color(255, 255, 102));
        pnlFundo.setName("pnlFundo"); // NOI18N

        lblTitulo.setBackground(new java.awt.Color(72, 136, 122));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(72, 136, 122));
        lblTitulo.setText("CONTROLE DE CLIENTES");
        lblTitulo.setName("lblTitulo"); // NOI18N

        pnlImg.setBackground(new java.awt.Color(72, 136, 122));
        pnlImg.setName("pnlImg"); // NOI18N
        pnlImg.setPreferredSize(new java.awt.Dimension(180, 180));

        imgLogo.setBackground(new java.awt.Color(72, 136, 122));
        imgLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Downloads\\estudo-dirigido-2-atividades-laboratorio-programacao-main\\02-atividade-pratica\\assets\\logo.png")); // NOI18N
        imgLogo.setMaximumSize(new java.awt.Dimension(180, 180));
        imgLogo.setMinimumSize(new java.awt.Dimension(180, 180));
        imgLogo.setName("imgLogo"); // NOI18N
        imgLogo.setPreferredSize(new java.awt.Dimension(180, 180));
        imgLogo.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlImgLayout = new javax.swing.GroupLayout(pnlImg);
        pnlImg.setLayout(pnlImgLayout);
        pnlImgLayout.setHorizontalGroup(
            pnlImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlImgLayout.setVerticalGroup(
            pnlImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(192, 192, 192))
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(pnlImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lblTitulo)
                .addGap(46, 46, 46)
                .addComponent(pnlImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pgcOptions.setBorder(null);
        pgcOptions.setName("pgcOptions"); // NOI18N

        pgArquivos.setText("Arquivo");
        pgArquivos.setName("pgArquivos"); // NOI18N

        optNovo.setText("Novo");
        optNovo.setName("optNovo"); // NOI18N
        optNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optNovoActionPerformed(evt);
            }
        });
        pgArquivos.add(optNovo);

        optSair.setText("Sair");
        optSair.setName("optSair"); // NOI18N
        pgArquivos.add(optSair);

        pgcOptions.add(pgArquivos);

        pgRelatorio.setText("Relatórios");
        pgRelatorio.setName("pgRelatorio"); // NOI18N
        pgcOptions.add(pgRelatorio);

        pgInfo.setText("Informações");
        pgInfo.setName("pgInfo"); // NOI18N
        pgcOptions.add(pgInfo);

        setJMenuBar(pgcOptions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optNovoActionPerformed
        NovaPessoa telaCadastro = new NovaPessoa();
        
        telaCadastro.setLocationRelativeTo(null);
        
        telaCadastro.setVisible(true);
               
    }//GEN-LAST:event_optNovoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem optNovo;
    private javax.swing.JMenuItem optSair;
    private javax.swing.JMenu pgArquivos;
    private javax.swing.JMenu pgInfo;
    private javax.swing.JMenu pgRelatorio;
    private javax.swing.JMenuBar pgcOptions;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JPanel pnlImg;
    // End of variables declaration//GEN-END:variables
}
