/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg01.atividade.pratica;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class NovaPessoa extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPessoa
     */
    
    gerirPessoas FGerirPessoas = new gerirPessoas();
    
    public NovaPessoa() {
        initComponents();
        this.setSize(600, 400);  
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        cbbTipoPessoa = new javax.swing.JComboBox<>();
        lblTipoPessoa = new javax.swing.JLabel();
        edtCPF = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtEstado = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        edtCargo = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        pnlFundo.setBackground(new java.awt.Color(255, 255, 102));
        pnlFundo.setMaximumSize(new java.awt.Dimension(600, 400));
        pnlFundo.setMinimumSize(new java.awt.Dimension(600, 400));
        pnlFundo.setName("pnlFundo"); // NOI18N

        lblTitulo.setBackground(new java.awt.Color(72, 136, 122));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(72, 136, 122));
        lblTitulo.setText("Nova Pessoa");
        lblTitulo.setName("lblTitulo"); // NOI18N

        cbbTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido", "Fornecedor", "Cliente" }));
        cbbTipoPessoa.setName("cbbTipoPessoa"); // NOI18N

        lblTipoPessoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipoPessoa.setText("Tipo Pessoa:");
        lblTipoPessoa.setName("lblTipoPessoa"); // NOI18N

        edtCPF.setName("edtCPF"); // NOI18N

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF.setText("CPF:");
        lblCPF.setName("lblCPF"); // NOI18N

        edtNome.setName("edtNome"); // NOI18N

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço:");
        lblEndereco.setName("lblEndereco"); // NOI18N

        edtEndereco.setName("edtEndereco"); // NOI18N

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");
        lblNome.setName("lblNome"); // NOI18N

        edtEstado.setName("edtEstado"); // NOI18N

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setText("Estado:");
        lblEstado.setName("lblEstado"); // NOI18N

        lblCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCargo.setText("Cargo:");
        lblCargo.setName("lblCargo"); // NOI18N

        btCadastrar.setText("Cadastrar");
        btCadastrar.setName("btCadastrar"); // NOI18N
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(edtEndereco)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTitulo)
                                .addComponent(cbbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTipoPessoa)
                                .addComponent(edtCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addComponent(lblCPF)
                                .addComponent(edtNome))
                            .addComponent(lblEndereco)))
                    .addComponent(lblNome))
                .addGap(57, 57, 57)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCargo)
                    .addComponent(lblEstado)
                    .addComponent(edtCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(edtEstado)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoPessoa)
                .addGap(2, 2, 2)
                .addComponent(cbbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblCargo))
                .addGap(3, 3, 3)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(lblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrar))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
       if (cbbTipoPessoa.getSelectedIndex() == 0){
           JOptionPane.showMessageDialog(this, "O campo tipo pessoa é obrigatório!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
           cbbTipoPessoa.requestFocus();
           return;
       }
       
       if (edtCPF.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "O campo CPF é obrigatório!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
           edtCPF.requestFocus();
           return;          
       }
       
       if (edtNome.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "O campo nome é obrigatório!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);;
           edtNome.requestFocus();
           return;
       }
       
       if (edtEndereco.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "O campo endereço é obrigatório!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
           edtEndereco.requestFocus();
           return;
       }
       
       if (edtEstado.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "O campo estado é obrigatório!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
           edtEstado.requestFocus();
           return;          
       }
       
       if (lblCargo.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "O campo cargo é obrigatório!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
           lblCargo.requestFocus();
           return;
       }
       
       if (cbbTipoPessoa.getSelectedIndex() == 1){
           
          String CPF      = edtCPF.getText();
          String Nome     = edtNome.getText();
          String Endereco = edtEndereco.getText();
          String Estado   = edtEstado.getText();
          String Cargo    = edtCargo.getText();
                  
          Fornecedor fornecedor = new Fornecedor(
                 CPF, 
                 Nome,
                 Endereco,
                 Estado, 
                 Cargo
          );
           
          FGerirPessoas.incluirFornecedor(fornecedor);
          
          cbbTipoPessoa.setSelectedIndex(0);
          edtCPF.setText("");
          edtNome.setText("");
          edtEndereco.setText("");
          edtEstado.setText("");
          edtCargo.setText("");
          
          JOptionPane.showMessageDialog(this, "Fornecedor cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE); 
       } else {
           
          String CPF      = edtCPF.getText();
          String Nome     = edtNome.getText();
          String Endereco = edtEndereco.getText();
          String Estado   = edtEstado.getText();
          String Cargo    = edtCargo.getText();
                  
          Cliente cliente = new Cliente(
                 CPF, 
                 Nome,
                 Endereco,
                 Estado, 
                 Cargo
          );
           
          FGerirPessoas.incluirCliente(cliente);
          
          cbbTipoPessoa.setSelectedIndex(0);
          edtCPF.setText("");
          edtNome.setText("");
          edtEndereco.setText("");
          edtEstado.setText("");
          edtCargo.setText("");
          
          JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE); 
       }
       

       
       
       
    }//GEN-LAST:event_btCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JComboBox<String> cbbTipoPessoa;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtCargo;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtEstado;
    private javax.swing.JTextField edtNome;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTipoPessoa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFundo;
    // End of variables declaration//GEN-END:variables
}
