/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg03.atividade.pratica;

import java.awt.event.KeyEvent;
import javax.swing.SwingConstants;

/**
 *
 * @author Pichau
 */
public class Janela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Janela.class.getName());

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        jlNome.setHorizontalAlignment(SwingConstants.RIGHT);
        jlEndereco.setHorizontalAlignment(SwingConstants.RIGHT);
        jlTelefone.setHorizontalAlignment(SwingConstants.RIGHT);
        jlCpf.setHorizontalAlignment(SwingConstants.RIGHT);
        jrbCorrente.setMnemonic(KeyEvent.VK_C);
        jrbPoupanca.setMnemonic(KeyEvent.VK_P);
        jbConsultar.setMnemonic(KeyEvent.VK_S);
        jbFechar.setMnemonic(KeyEvent.VK_F);
        jbAtualizar.setMnemonic(KeyEvent.VK_A);
        jrbCorrente.setSelected(true);
        bgContas.add(jrbCorrente);
        bgContas.add(jrbPoupanca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgContas = new javax.swing.ButtonGroup();
        jlAgencia = new javax.swing.JLabel();
        jtfConta = new javax.swing.JTextField();
        jlConta = new javax.swing.JLabel();
        jtfAgencia1 = new javax.swing.JTextField();
        jSeparator01 = new javax.swing.JSeparator();
        jlNome = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlEndereco = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfAgencia3 = new javax.swing.JTextField();
        jtfTelefone = new javax.swing.JTextField();
        jtfCpf = new javax.swing.JTextField();
        jrbCorrente = new javax.swing.JRadioButton();
        jrbPoupanca = new javax.swing.JRadioButton();
        jSeparator02 = new javax.swing.JSeparator();
        jbFechar = new javax.swing.JToggleButton();
        jbConsultar = new javax.swing.JToggleButton();
        jbAtualizar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laboratório de Programação");
        setMaximumSize(new java.awt.Dimension(400, 255));
        setMinimumSize(new java.awt.Dimension(400, 255));
        setPreferredSize(new java.awt.Dimension(400, 255));
        setResizable(false);

        jlAgencia.setText("Código da Agência:");
        jlAgencia.setPreferredSize(new java.awt.Dimension(110, 18));

        jtfConta.setMinimumSize(new java.awt.Dimension(60, 20));
        jtfConta.setPreferredSize(new java.awt.Dimension(60, 20));

        jlConta.setText("Número da Conta:");
        jlConta.setMaximumSize(new java.awt.Dimension(105, 18));
        jlConta.setMinimumSize(new java.awt.Dimension(105, 18));
        jlConta.setPreferredSize(new java.awt.Dimension(105, 18));

        jtfAgencia1.setMinimumSize(new java.awt.Dimension(50, 20));
        jtfAgencia1.setPreferredSize(new java.awt.Dimension(50, 20));

        jSeparator01.setMaximumSize(new java.awt.Dimension(365, 10));
        jSeparator01.setMinimumSize(new java.awt.Dimension(365, 10));
        jSeparator01.setPreferredSize(new java.awt.Dimension(365, 10));

        jlNome.setText("Nome:");
        jlNome.setMaximumSize(new java.awt.Dimension(60, 18));
        jlNome.setMinimumSize(new java.awt.Dimension(60, 18));
        jlNome.setPreferredSize(new java.awt.Dimension(60, 18));

        jlTelefone.setText("Telefone:");
        jlTelefone.setMaximumSize(new java.awt.Dimension(60, 18));
        jlTelefone.setMinimumSize(new java.awt.Dimension(60, 18));
        jlTelefone.setPreferredSize(new java.awt.Dimension(60, 18));

        jlEndereco.setText("Endereço:");
        jlEndereco.setMaximumSize(new java.awt.Dimension(60, 18));
        jlEndereco.setMinimumSize(new java.awt.Dimension(60, 18));
        jlEndereco.setName(""); // NOI18N
        jlEndereco.setPreferredSize(new java.awt.Dimension(60, 18));

        jlCpf.setText("CEP:");
        jlCpf.setMaximumSize(new java.awt.Dimension(60, 18));
        jlCpf.setMinimumSize(new java.awt.Dimension(60, 18));
        jlCpf.setPreferredSize(new java.awt.Dimension(60, 18));

        jtfNome.setMaximumSize(new java.awt.Dimension(300, 20));
        jtfNome.setMinimumSize(new java.awt.Dimension(300, 20));
        jtfNome.setPreferredSize(new java.awt.Dimension(300, 20));

        jtfAgencia3.setMaximumSize(new java.awt.Dimension(300, 20));
        jtfAgencia3.setMinimumSize(new java.awt.Dimension(300, 20));
        jtfAgencia3.setPreferredSize(new java.awt.Dimension(300, 20));

        jtfTelefone.setMaximumSize(new java.awt.Dimension(300, 20));
        jtfTelefone.setMinimumSize(new java.awt.Dimension(300, 20));
        jtfTelefone.setName(""); // NOI18N
        jtfTelefone.setPreferredSize(new java.awt.Dimension(300, 20));
        jtfTelefone.setRequestFocusEnabled(false);

        jtfCpf.setMaximumSize(new java.awt.Dimension(300, 20));
        jtfCpf.setMinimumSize(new java.awt.Dimension(300, 20));
        jtfCpf.setPreferredSize(new java.awt.Dimension(300, 20));

        jrbCorrente.setText("Conta Corrente");
        jrbCorrente.setMaximumSize(new java.awt.Dimension(111, 20));
        jrbCorrente.setMinimumSize(new java.awt.Dimension(111, 20));
        jrbCorrente.setPreferredSize(new java.awt.Dimension(111, 20));

        jrbPoupanca.setText("Conta Poupança");
        jrbPoupanca.setMaximumSize(new java.awt.Dimension(118, 20));
        jrbPoupanca.setMinimumSize(new java.awt.Dimension(118, 20));
        jrbPoupanca.setPreferredSize(new java.awt.Dimension(118, 20));

        jSeparator02.setMaximumSize(new java.awt.Dimension(365, 10));
        jSeparator02.setMinimumSize(new java.awt.Dimension(365, 10));
        jSeparator02.setPreferredSize(new java.awt.Dimension(365, 10));

        jbFechar.setText("Fechar");
        jbFechar.setToolTipText("Fechar");
        jbFechar.setMaximumSize(new java.awt.Dimension(100, 23));
        jbFechar.setMinimumSize(new java.awt.Dimension(100, 23));
        jbFechar.setPreferredSize(new java.awt.Dimension(100, 23));

        jbConsultar.setText("Consultar");
        jbConsultar.setMaximumSize(new java.awt.Dimension(100, 23));
        jbConsultar.setMinimumSize(new java.awt.Dimension(100, 23));
        jbConsultar.setPreferredSize(new java.awt.Dimension(100, 23));

        jbAtualizar.setText("Atualizar");
        jbAtualizar.setMaximumSize(new java.awt.Dimension(100, 23));
        jbAtualizar.setMinimumSize(new java.awt.Dimension(100, 23));
        jbAtualizar.setPreferredSize(new java.awt.Dimension(100, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jbConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfAgencia3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jrbCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrbPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jlAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfAgencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAgencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator01, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAgencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator02, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Janela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgContas;
    private javax.swing.JSeparator jSeparator01;
    private javax.swing.JSeparator jSeparator02;
    private javax.swing.JToggleButton jbAtualizar;
    private javax.swing.JToggleButton jbConsultar;
    private javax.swing.JToggleButton jbFechar;
    private javax.swing.JLabel jlAgencia;
    private javax.swing.JLabel jlConta;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JRadioButton jrbCorrente;
    private javax.swing.JRadioButton jrbPoupanca;
    private javax.swing.JTextField jtfAgencia1;
    private javax.swing.JTextField jtfAgencia3;
    private javax.swing.JTextField jtfConta;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables
}
